[2025-05-03T15:13:29.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T15:13:29.153+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T15:13:29.172+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T15:13:29.173+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-03T15:13:29.195+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-05-02 00:00:00+00:00
[2025-05-03T15:13:29.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp8ktvlq8x']
[2025-05-03T15:13:29.209+0000] {standard_task_runner.py:105} INFO - Job 168: Subtask load_task
[2025-05-03T15:13:29.211+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-03T15:13:29.213+0000] {standard_task_runner.py:72} INFO - Started process 190 to run task
[2025-05-03T15:13:29.285+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-05-02T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-05-03T15:13:29.425+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T15:13:29.427+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-03T15:13:29.468+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-05-03', 17.0, 26.2, 0.3, 80], ['2025-05-04', 9.6, 17.4, 0.6, 61], ['2025-05-05', 6.7, 16.0, 0.1, 3], ['2025-05-06', 6.9, 16.7, 0.0, 3], ['2025-05-07', 8.7, 17.2, 0.0, 3], ['2025-05-08', 9.5, 20.0, 0.0, 3], ['2025-05-09', 9.6, 20.4, 0.0, 1]]
[2025-05-03T15:13:29.484+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-03T15:13:29.500+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-03T15:13:29.501+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-05-02T00:00:00+00:00, execution_date=20250502T000000, start_date=20250503T151329, end_date=20250503T151329
[2025-05-03T15:13:29.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-03T15:13:29.619+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T15:13:29.622+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
