[2025-04-18T00:00:05.725+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T00:00:05.762+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-17T00:00:00+00:00 [queued]>
[2025-04-18T00:00:05.779+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-17T00:00:00+00:00 [queued]>
[2025-04-18T00:00:05.781+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-18T00:00:05.805+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-17 00:00:00+00:00
[2025-04-18T00:00:05.818+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-17T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpnpvxd85i']
[2025-04-18T00:00:05.821+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask load_task
[2025-04-18T00:00:05.824+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1310) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T00:00:05.826+0000] {standard_task_runner.py:72} INFO - Started process 1311 to run task
[2025-04-18T00:00:05.901+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-17T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-18T00:00:06.043+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T00:00:00+00:00'
[2025-04-18T00:00:06.045+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T00:00:06.096+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-18', 6.8, 18.0, 0.0, 3], ['2025-04-19', 9.7, 19.5, 5.6, 63], ['2025-04-20', 10.6, 16.8, 0.6, 80], ['2025-04-21', 9.2, 18.7, 7.2, 80], ['2025-04-22', 10.1, 17.7, 1.8, 80], ['2025-04-23', 10.1, 13.7, 10.8, 80], ['2025-04-24', 8.2, 17.5, 0.0, 3]]
[2025-04-18T00:00:06.119+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T00:00:06.136+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T00:00:06.137+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-17T00:00:00+00:00, execution_date=20250417T000000, start_date=20250418T000005, end_date=20250418T000006
[2025-04-18T00:00:06.204+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T00:00:06.231+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T00:00:06.234+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
