[2025-04-26T01:06:14.281+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T01:06:14.318+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-26T01:06:14.351+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-26T01:06:14.354+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-26T01:06:14.391+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-25 00:00:00+00:00
[2025-04-26T01:06:14.407+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-25T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_4zo6wjj']
[2025-04-26T01:06:14.419+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask load_task
[2025-04-26T01:06:14.422+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-26T01:06:14.426+0000] {standard_task_runner.py:72} INFO - Started process 201 to run task
[2025-04-26T01:06:14.536+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-25T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-26T01:06:14.791+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-25T00:00:00+00:00'
[2025-04-26T01:06:14.793+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-26T01:06:14.893+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-26', 8.6, 19.3, 0.0, 3], ['2025-04-27', 11.5, 20.7, 0.0, 3], ['2025-04-28', 11.0, 21.5, 0.0, 2], ['2025-04-29', 11.5, 23.8, 0.0, 2], ['2025-04-30', 13.5, 23.8, 0.9, 3], ['2025-05-01', 13.4, 23.1, 0.3, 45], ['2025-05-02', 14.1, 19.6, 6.6, 95]]
[2025-04-26T01:06:14.977+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-26T01:06:15.001+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-26T01:06:15.005+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-25T00:00:00+00:00, execution_date=20250425T000000, start_date=20250426T010614, end_date=20250426T010615
[2025-04-26T01:06:15.314+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-26T01:06:15.398+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-26T01:06:15.439+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
