[2025-05-08T12:25:19.981+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T12:25:20.007+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T12:25:20.022+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T12:25:20.023+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-08T12:25:20.040+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-05-07 00:00:00+00:00
[2025-05-08T12:25:20.049+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-05-07T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpana65kdm']
[2025-05-08T12:25:20.051+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask load_task
[2025-05-08T12:25:20.053+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-08T12:25:20.054+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2025-05-08T12:25:20.105+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-05-07T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-05-08T12:25:20.199+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-07T00:00:00+00:00'
[2025-05-08T12:25:20.200+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T12:25:20.226+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-05-08', 9.3, 19.0, 0.0, 3], ['2025-05-09', 9.8, 19.9, 0.0, 3], ['2025-05-10', 10.9, 22.7, 0.0, 2], ['2025-05-11', 13.6, 24.5, 0.6, 80], ['2025-05-12', 14.0, 22.8, 5.1, 95], ['2025-05-13', 14.6, 20.8, 5.4, 80], ['2025-05-14', 10.1, 20.4, 0.0, 3]]
[2025-05-08T12:25:20.237+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-08T12:25:20.248+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T12:25:20.249+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-05-07T00:00:00+00:00, execution_date=20250507T000000, start_date=20250508T122520, end_date=20250508T122520
[2025-05-08T12:25:20.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-08T12:25:20.330+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T12:25:20.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
