[2025-05-02T00:37:13.779+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T00:37:13.821+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T00:37:13.843+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T00:37:13.844+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-02T00:37:13.862+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-05-01 00:00:00+00:00
[2025-05-02T00:37:13.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmps4vxnt57']
[2025-05-02T00:37:13.882+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask load_task
[2025-05-02T00:37:13.883+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1365) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T00:37:13.884+0000] {standard_task_runner.py:72} INFO - Started process 1366 to run task
[2025-05-02T00:37:13.943+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-05-01T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-05-02T00:37:14.087+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T00:37:14.093+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-02T00:37:14.132+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-05-02', 17.4, 28.1, 0.0, 3], ['2025-05-03', 16.6, 23.7, 9.6, 95], ['2025-05-04', 10.5, 16.9, 0.6, 61], ['2025-05-05', 6.4, 17.3, 0.0, 1], ['2025-05-06', 7.3, 17.5, 0.0, 2], ['2025-05-07', 6.6, 16.7, 0.0, 2], ['2025-05-08', 7.3, 16.6, 0.0, 61]]
[2025-05-02T00:37:14.162+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-02T00:37:14.182+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-02T00:37:14.184+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-05-01T00:00:00+00:00, execution_date=20250501T000000, start_date=20250502T003713, end_date=20250502T003714
[2025-05-02T00:37:14.262+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-02T00:37:14.284+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T00:37:14.287+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
