[2025-04-12T21:10:20.625+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T21:10:20.671+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-12T21:10:20.708+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-12T21:10:20.709+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-12T21:10:20.777+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-11 00:00:00+00:00
[2025-04-12T21:10:20.791+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-11T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpz1wdpa3g']
[2025-04-12T21:10:20.796+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask load_task
[2025-04-12T21:10:20.804+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-12T21:10:20.805+0000] {standard_task_runner.py:72} INFO - Started process 186 to run task
[2025-04-12T21:10:20.914+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-11T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-12T21:10:21.096+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T00:00:00+00:00'
[2025-04-12T21:10:21.101+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-12T21:10:21.161+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-12', 10.4, 21.6, 2.0, 61], ['2025-04-13', 13.7, 19.9, 1.7, 61], ['2025-04-14', 10.4, 19.8, 0.0, 3], ['2025-04-15', 11.0, 17.9, 4.2, 80], ['2025-04-16', 8.7, 15.1, 0.0, 3], ['2025-04-17', 7.8, 15.6, 0.3, 61], ['2025-04-18', 10.4, 18.6, 0.3, 3]]
[2025-04-12T21:10:21.197+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T21:10:21.232+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-12T21:10:21.234+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-11T00:00:00+00:00, execution_date=20250411T000000, start_date=20250412T211020, end_date=20250412T211021
[2025-04-12T21:10:21.323+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T21:10:21.363+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T21:10:21.372+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
