[2025-04-21T00:00:03.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T00:00:03.889+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-20T00:00:00+00:00 [queued]>
[2025-04-21T00:00:03.902+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-20T00:00:00+00:00 [queued]>
[2025-04-21T00:00:03.903+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-21T00:00:03.922+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-20 00:00:00+00:00
[2025-04-21T00:00:03.930+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-20T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp9x0vgokp']
[2025-04-21T00:00:03.933+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask load_task
[2025-04-21T00:00:03.933+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2021) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-21T00:00:03.934+0000] {standard_task_runner.py:72} INFO - Started process 2022 to run task
[2025-04-21T00:00:03.989+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-20T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-21T00:00:04.084+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-20T00:00:00+00:00'
[2025-04-21T00:00:04.085+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T00:00:04.112+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-21', 10.5, 15.5, 1.7, 80], ['2025-04-22', 10.9, 16.9, 0.2, 80], ['2025-04-23', 8.5, 13.8, 1.7, 61], ['2025-04-24', 9.6, 18.6, 0.0, 3], ['2025-04-25', 9.7, 20.8, 0.0, 3], ['2025-04-26', 9.9, 19.4, 0.0, 3], ['2025-04-27', 9.1, 19.1, 0.0, 2]]
[2025-04-21T00:00:04.132+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-21T00:00:04.143+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T00:00:04.144+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-20T00:00:00+00:00, execution_date=20250420T000000, start_date=20250421T000003, end_date=20250421T000004
[2025-04-21T00:00:04.189+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-21T00:00:04.209+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T00:00:04.211+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
