[2025-05-01T11:29:58.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T11:29:58.181+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-30T00:00:00+00:00 [queued]>
[2025-05-01T11:29:58.200+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-30T00:00:00+00:00 [queued]>
[2025-05-01T11:29:58.201+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-01T11:29:58.217+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-30 00:00:00+00:00
[2025-05-01T11:29:58.229+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-30T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp5pullp6x']
[2025-05-01T11:29:58.232+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask load_task
[2025-05-01T11:29:58.232+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T11:29:58.233+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2025-05-01T11:29:58.289+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-30T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-05-01T11:29:58.398+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-30T00:00:00+00:00'
[2025-05-01T11:29:58.399+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-01T11:29:58.430+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-05-01', 15.4, 29.9, 0.0, 3], ['2025-05-02', 17.5, 28.6, 0.0, 3], ['2025-05-03', 17.2, 23.4, 3.9, 80], ['2025-05-04', 10.5, 16.6, 0.6, 61], ['2025-05-05', 5.7, 15.7, 0.0, 3], ['2025-05-06', 6.2, 15.7, 0.0, 3], ['2025-05-07', 6.1, 17.5, 0.0, 3]]
[2025-05-01T11:29:58.450+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-01T11:29:58.463+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-01T11:29:58.464+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-30T00:00:00+00:00, execution_date=20250430T000000, start_date=20250501T112958, end_date=20250501T112958
[2025-05-01T11:29:58.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-01T11:29:58.548+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T11:29:58.551+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
