[2025-05-10T00:50:38.644+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-10T00:50:38.673+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-09T00:00:00+00:00 [queued]>
[2025-05-10T00:50:38.689+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-05-09T00:00:00+00:00 [queued]>
[2025-05-10T00:50:38.690+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-10T00:50:38.707+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-05-09 00:00:00+00:00
[2025-05-10T00:50:38.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-05-09T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp24ur9a_r']
[2025-05-10T00:50:38.720+0000] {standard_task_runner.py:105} INFO - Job 193: Subtask load_task
[2025-05-10T00:50:38.721+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1730) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-10T00:50:38.722+0000] {standard_task_runner.py:72} INFO - Started process 1731 to run task
[2025-05-10T00:50:38.779+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-05-09T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-05-10T00:50:38.878+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-09T00:00:00+00:00'
[2025-05-10T00:50:38.879+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-10T00:50:38.906+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-05-10', 11.2, 23.5, 0.0, 2], ['2025-05-11', 13.7, 25.1, 0.0, 3], ['2025-05-12', 14.3, 17.7, 8.5, 61], ['2025-05-13', 12.1, 20.4, 1.5, 80], ['2025-05-14', 12.9, 24.7, 0.0, 3], ['2025-05-15', 11.5, 23.9, 0.0, 2], ['2025-05-16', 7.9, 23.5, 0.0, 2]]
[2025-05-10T00:50:38.928+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-10T00:50:38.940+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-10T00:50:38.941+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-05-09T00:00:00+00:00, execution_date=20250509T000000, start_date=20250510T005038, end_date=20250510T005038
[2025-05-10T00:50:38.979+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-10T00:50:38.999+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-10T00:50:39.001+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
